# Matrix, Vector & NumPy Basics

This notebook covers the fundamentals of:
- **Vectors** - 1D arrays and their operations
- **Matrices** - 2D arrays and linear algebra basics
- **NumPy** - Essential functions for numerical computing
- **Tensors** - Generalization of matrices to higher dimensions

These concepts are foundational for Data Science, Machine Learning, and AI. We will go through each concept with clear explanations and code examples.

In [5]:
import numpy as np
from numpy.exceptions import AxisError
print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.4.1


---
## 1. Vectors

A **vector** is essentially a list of numbers. In the world of Math and Physics, it represents a quantity that has both magnitude and direction.

In **Machine Learning**, we use vectors to represent 'features'. For example, a house can be represented as a vector: `[Price, Size, No. of Rooms]`.

In [6]:
# Creating vectors
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

print("Vector v1:", v1)
print("Vector v2:", v2)
print("Shape:", v1.shape)
print("Dimension:", v1.ndim)

Vector v1: [1 2 3 4 5]
Vector v2: [ 6  7  8  9 10]
Shape: (5,)
Dimension: 1


### 1.1 Vector Operations

We can perform arithmetic operations on vectors. In NumPy, these operations are **element-wise**.

This means that if you add two vectors, the first element of the first vector is added to the first element of the second vector, and so on. The same logic applies to subtraction, multiplication, and division.

In [7]:
# Basic arithmetic operations (element-wise)
print("Addition (v1 + v2):", v1 + v2)
print("Subtraction (v2 - v1):", v2 - v1)
print("Multiplication (v1 * v2):", v1 * v2)
print("Division (v2 / v1):", v2 / v1)
print("Scalar multiplication (v1 * 3):", v1 * 3)

Addition (v1 + v2): [ 7  9 11 13 15]
Subtraction (v2 - v1): [5 5 5 5 5]
Multiplication (v1 * v2): [ 6 14 24 36 50]
Division (v2 / v1): [6.         3.5        2.66666667 2.25       2.        ]
Scalar multiplication (v1 * 3): [ 3  6  9 12 15]


### 1.2 Dot Product

The **Dot Product** is one of the most important operations in Linear Algebra and AI (especially in Neural Networks).

Mathematically, it is the sum of the products of corresponding elements:
$$ a \cdot b = \sum_{i=1}^{n} a_i b_i = a_1b_1 + a_2b_2 + ... + a_nb_n $$

In NumPy, we use `np.dot()` or the `@` symbol.

In [8]:
# Dot Product - fundamental in ML (weights * features)
dot_product = np.dot(v1, v2)
print("Dot Product (v1 · v2):", dot_product)

# Alternative: using @ operator
print("Using @ operator:", v1 @ v2)

Dot Product (v1 · v2): 130
Using @ operator: 130


### 1.3 Magnitude & Unit Vector

**Magnitude (or Norm)** is the length of the vector. We calculate it using the Pythagorean theorem for n-dimensions (Euclidean Norm).

A **Unit Vector** is a vector with a magnitude of length 1. It points in the same direction as the original vector but has a standard length. We find it by dividing the vector by its magnitude.

In [9]:
# Vector magnitude (length/norm)
magnitude = np.linalg.norm(v1)
print("Magnitude of v1:", magnitude)

# Unit vector (normalized)
unit_vector = v1 / magnitude
print("Unit vector:", unit_vector)
print("Magnitude of unit vector:", np.linalg.norm(unit_vector))

Magnitude of v1: 7.416198487095663
Unit vector: [0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]
Magnitude of unit vector: 1.0


---
## 2. Matrices

A **matrix** is a 2-dimensional grid of numbers (rows and columns). 

In Data Science, a DataFrame is basically a matrix where:
- Rows = Samples (e.g., Users, Patients)
- Columns = Features (e.g., Age, Zip Code)

In [10]:
# Creating matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:")
print(A)
print("\nShape:", A.shape)
print("Dimensions:", A.ndim)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Dimensions: 2


### 2.1 Special Matrices

NumPy provides helper functions to create common matrices easily:
- **Zero Matrix:** Filled with 0s (Initialization)
- **Ones Matrix:** Filled with 1s
- **Identity Matrix:** Diagonal is 1, rest 0 ($I$)
- **Diagonal Matrix:** Custom values on the diagonal

In [11]:
# Zero matrix
zeros = np.zeros((3, 3))
print("Zero Matrix:\n", zeros)

# Ones matrix
ones = np.ones((2, 4))
print("\nOnes Matrix:\n", ones)

# Identity matrix (diagonal = 1)
identity = np.eye(3)
print("\nIdentity Matrix:\n", identity)

# Diagonal matrix
diag = np.diag([1, 2, 3, 4])
print("\nDiagonal Matrix:\n", diag)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 2.2 Matrix Operations & Expected Errors

**Important Mathematical Concept:**

To multiply two matrices $A$ (shape $m \times n$) and $B$ (shape $p \times q$), the inner dimensions must match: **$n$ must equal $p$**.
The resulting matrix will have shape **$m \times q$**.

In [12]:
# Element-wise operations (Shapes must be identical)
print("A + B (element-wise):")
print(A + B)

print("\nA * B (element-wise):")
print(A * B)

A + B (element-wise):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

A * B (element-wise):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [13]:
# Matrix Multiplication (Dot Product)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # Shape (3, 2)

D = np.array([[7, 8, 9],
              [10, 11, 12]]) # Shape (2, 3)

print(f"C shape: {C.shape}")
print(f"D shape: {D.shape}")

# (3x2) @ (2x3) -> (3x3) Result
print("\nMatrix multiplication C @ D:")
print(C @ D)  # or np.dot(C, D)

C shape: (3, 2)
D shape: (2, 3)

Matrix multiplication C @ D:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


### ⚠️ Common Error: Dimension Mismatch

If you try to multiply matrices with incompatible shapes, NumPy will raise a `ValueError`. This is the most common error in Deep Learning when layers don't align.

In [14]:
# Let's try to multiply C (3x2) with A (3x3)
# Inner dimensions: 2 != 3 -> This will fail!

try:
    print(C @ A)
except ValueError as e:
    print("\u274c Error Caught!:", e)
    print("Explanation: You cannot multiply (3x2) by (3x3). The inner numbers (2 and 3) don't match.")

❌ Error Caught!: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
Explanation: You cannot multiply (3x2) by (3x3). The inner numbers (2 and 3) don't match.


### 2.3 Transpose

**Transposing** a matrix means to flip it over its diagonal. Rows become columns, and columns become rows. We denote it as $A^T$.

In [15]:
# Transpose
print("Original C:")
print(C)
print("\nTranspose C.T:")
print(C.T)

Original C:
[[1 2]
 [3 4]
 [5 6]]

Transpose C.T:
[[1 3 5]
 [2 4 6]]


### 2.4 Matrix Properties

- **Determinant:** A scalar value that describes properties of the matrix (like scaling factor).
- **Trace:** Sum of elements on the main diagonal.
- **Rank:** The number of linearly independent rows or columns.

In [16]:
(4*3)-(2*1)

10

In [46]:
M = np.array([[4, 2],
              [1, 3]])

# Determinant
det = np.linalg.det(M)
print("Determinant:", det)

# Trace (sum of diagonal)
trace = np.trace(M)
print("Trace:", trace)

# Rank
rank = np.linalg.matrix_rank(M)
print("Rank:", rank)

Determinant: 10.000000000000002
Trace: 7
Rank: 2


The term (ad) represents the area expansion along the axes, while (bc) represents the area reduction due to the skewing (rotation/shear) of the axes. The Minus (-) sign accounts for the 'lost' area because the vectors are no longer perpendicular.

SIZE 

In [47]:
# Inverse (only for square matrices with det != 0)
M_inv = np.linalg.inv(M)
print("Inverse of M:\n", M_inv)

# Verify: M @ M_inv = Identity
print("\nM @ M_inv (should be Identity):")
print(np.round(M @ M_inv, 10))

Inverse of M:
 [[ 0.3 -0.2]
 [-0.1  0.4]]

M @ M_inv (should be Identity):
[[ 1.  0.]
 [-0.  1.]]


### 2.6 Linear Transformations

This is the "Aha!" moment of Linear Algebra. 
A matrix is not just a table of numbers; it is a **Transformation Logic**.

When you multiply a vector $v$ by a matrix $A$ (i.e., $A \times v$), the matrix **moves** the vector to a new position. It transforms the vector space.

Common transformations include:
- **Scaling:** Stretching or shrinking
- **Rotation:** Spinning the vector
- **Shearing:** Slanting the grid

In [19]:
# Example: Scaling Transformation
# Let's take a vector [2, 1]
v = np.array([2, 1])

# Scaling Matrix (scales x by 2, y by 0.5)
S = np.array([[2, 0],
              [0, 0.5]])

transformed_v = S @ v

print(f"Original Vector: {v}")
print(f"Scaling Matrix:\n{S}")
print(f"Transformed Vector (Scaled): {transformed_v}")
print("Explanation: x became 2*2=4, y became 1*0.5=0.5")

Original Vector: [2 1]
Scaling Matrix:
[[2.  0. ]
 [0.  0.5]]
Transformed Vector (Scaled): [4.  0.5]
Explanation: x became 2*2=4, y became 1*0.5=0.5


### 2.7 Eigenvalues & Eigenvectors

These are advanced but critical concepts.
- **Eigenvector:** A vector that does not change direction during a linear transformation.
- **Eigenvalue:** The factor by which the eigenvector is scaled.

These are heavily used in PCA (Principal Component Analysis) for dimensionality reduction.

In [20]:
eigenvalues, eigenvectors = np.linalg.eig(M)
print("Eigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


---
## 3. NumPy Essentials & Common Errors

### 3.1 Common NumPy Errors & How to Fix Them

Working with arrays often leads to shapes mismatch. Here are the most common ones:

In [48]:
# Error 1: Broadcasting Error
# Trying to add arrays of different shapes that cannot interpret each other
a = np.array([1, 2, 3])
b = np.array([1, 2])

try:
    print(a + b)
except ValueError as e:
    print("\u274c Broadcasting Error:", e)
    print("Fix: Ensure arrays have same shape or compatible dimensions (e.g., (3,1) and (1,3))")

❌ Broadcasting Error: operands could not be broadcast together with shapes (3,) (2,) 
Fix: Ensure arrays have same shape or compatible dimensions (e.g., (3,1) and (1,3))


#### ✅ Solution 1: Fix Broadcasting Error

There are several ways to fix broadcasting errors:
1. **Resize the smaller array** to match the larger one
2. **Use compatible shapes** that can be broadcasted
3. **Slice or pad arrays** to make them compatible

In [22]:
# Solution 1a: Resize/pad the smaller array
a = np.array([1, 2, 3])
b = np.array([1, 2])

# Option 1: Pad b with a zero
b_padded = np.pad(b, (0, 1), constant_values=0)  # [1, 2, 0]
print("✅ Solution 1a (padding):", a + b_padded)

# Option 2: Use only compatible elements (slicing)
print("✅ Solution 1b (slicing):", a[:2] + b)  # Only use first 2 elements of a

# Option 3: Resize b to match a's shape
b_resized = np.resize(b, a.shape)  # Repeats values to fill [1, 2, 1]
print("✅ Solution 1c (resizing):", a + b_resized)

✅ Solution 1a (padding): [2 4 3]
✅ Solution 1b (slicing): [2 4]
✅ Solution 1c (resizing): [2 4 4]


In [23]:
# Error 2: Dimension Mismatch in Reshape
# Total elements must remain constant
arr = np.arange(10) # 10 elements

try:
    print(arr.reshape(3, 3)) # 3x3 = 9 elements
except ValueError as e:
    print("\u274c Reshape Error:", e)
    print("Fix: 3x3 requires 9 elements, but we have 10. Try reshape(2, 5).")

❌ Reshape Error: cannot reshape array of size 10 into shape (3,3)
Fix: 3x3 requires 9 elements, but we have 10. Try reshape(2, 5).


#### ✅ Solution 2: Fix Reshape Error

To fix reshape errors, ensure the total number of elements matches:
- **Calculate valid shapes**: rows × columns must equal total elements
- **Use -1 for auto-calculation**: NumPy can infer one dimension
- **Slice or pad** if necessary

In [24]:
arr = np.arange(10)  # 10 elements

# Solution 2a: Use valid dimensions that multiply to 10
print("✅ Solution 2a (2x5):\n", arr.reshape(2, 5))
print("\n✅ Solution 2a (5x2):\n", arr.reshape(5, 2))

# Solution 2b: Use -1 to auto-calculate one dimension
print("\n✅ Solution 2b (auto 2x?):\n", arr.reshape(2, -1))  # NumPy calculates: 2×5=10
print("\n✅ Solution 2b (auto ?x5):\n", arr.reshape(-1, 5))  # NumPy calculates: 2×5=10

# Solution 2c: If you really need (3,3), slice or pad first
arr_9 = arr[:9]  # Take only first 9 elements
print("\n✅ Solution 2c (slice then reshape):\n", arr_9.reshape(3, 3))

# Solution 2d: Pad to get 12 elements, then reshape to (3,4)
arr_12 = np.pad(arr, (0, 2), constant_values=0)  # Add 2 zeros
print("\n✅ Solution 2d (pad then reshape):\n", arr_12.reshape(3, 4))

✅ Solution 2a (2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]

✅ Solution 2a (5x2):
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

✅ Solution 2b (auto 2x?):
 [[0 1 2 3 4]
 [5 6 7 8 9]]

✅ Solution 2b (auto ?x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]

✅ Solution 2c (slice then reshape):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

✅ Solution 2d (pad then reshape):
 [[0 1 2 3]
 [4 5 6 7]
 [8 9 0 0]]


In [25]:
# Error 3: Axis Error
# Asking for an axis that doesn't exist
arr_2d = np.array([[1, 2], [3, 4]]) # 2 dimensions (0 and 1)

try:
    print(np.sum(arr_2d, axis=2))
except AxisError as e:
    print("❌ Axis Error:", e)
    print("Fix: For a 2D array, you can only use axis=0 (rows) or axis=1 (cols).")

❌ Axis Error: axis 2 is out of bounds for array of dimension 2
Fix: For a 2D array, you can only use axis=0 (rows) or axis=1 (cols).


#### ✅ Solution 3: Fix Axis Error

To avoid axis errors:
- **Check array dimensions** first using `.ndim`
- **Valid axes** are from 0 to ndim-1
- **Use None or omit axis** to operate on all elements

In [26]:
arr_2d = np.array([[1, 2], [3, 4]])  # 2 dimensions (0 and 1)

print(f"Array shape: {arr_2d.shape}")
print(f"Number of dimensions: {arr_2d.ndim}")
print(f"Valid axes: 0 to {arr_2d.ndim - 1}\n")

# Solution 3a: Use axis=0 (sum along rows, result is 1D)
print("✅ Solution 3a (axis=0 - sum columns):", np.sum(arr_2d, axis=0))

# Solution 3b: Use axis=1 (sum along columns, result is 1D)
print("✅ Solution 3b (axis=1 - sum rows):", np.sum(arr_2d, axis=1))

# Solution 3c: No axis specified (sum all elements)
print("✅ Solution 3c (no axis - sum all):", np.sum(arr_2d))

# Visualization of what each axis means
print("\n--- Understanding Axes ---")
print("axis=0 → operates DOWN the rows (collapses rows)")
print("axis=1 → operates ACROSS the columns (collapses columns)")

# For 3D arrays
arr_3d = np.random.randint(1, 10, size=(2, 3, 4))
print(f"\n3D Array shape: {arr_3d.shape} has {arr_3d.ndim} dimensions")
print(f"Valid axes: 0, 1, 2")
print(f"axis=0 result shape: {np.sum(arr_3d, axis=0).shape}")
print(f"axis=1 result shape: {np.sum(arr_3d, axis=1).shape}")
print(f"axis=2 result shape: {np.sum(arr_3d, axis=2).shape}")

Array shape: (2, 2)
Number of dimensions: 2
Valid axes: 0 to 1

✅ Solution 3a (axis=0 - sum columns): [4 6]
✅ Solution 3b (axis=1 - sum rows): [3 7]
✅ Solution 3c (no axis - sum all): 10

--- Understanding Axes ---
axis=0 → operates DOWN the rows (collapses rows)
axis=1 → operates ACROSS the columns (collapses columns)

3D Array shape: (2, 3, 4) has 3 dimensions
Valid axes: 0, 1, 2
axis=0 result shape: (3, 4)
axis=1 result shape: (2, 4)
axis=2 result shape: (2, 3)


### 3.2 Array Creation

NumPy offers efficient ways to generate arrays:
- **`np.arange`**: Like Python's `range` but returns an array.
- **`np.linspace`**: Generates a set number of points evenly spaced between two values.
- **`np.random`**: Very useful for initializing weights in Neural Networks.

In [27]:
# Using arange
arr1 = np.arange(0, 10, 2)  # start, stop, step
print("arange(0,10,2):", arr1)

# Using linspace (evenly spaced)
arr2 = np.linspace(0, 1, 5)  # start, stop, num_points
print("linspace(0,1,5):", arr2)

# Random arrays
rand_uniform = np.random.rand(3, 3)  # uniform [0,1)
rand_normal = np.random.randn(3, 3)  # standard normal
rand_int = np.random.randint(1, 10, size=(3, 3))  # random integers

print("\nRandom integers (1-10):")
print(rand_int)

arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

Random integers (1-10):
[[9 4 9]
 [7 2 1]
 [5 4 6]]


### 3.3 Reshaping & Stacking

- **Reshape**: Changes the structure of the data without changing the data itself. Essential for preparing data for models.
- **Flatten**: Converts a multi-dimensional matrix into a long 1D vector.
- **Stack**: Combines multiple arrays together (Vertically or Horizontally).

In [28]:
arr = np.arange(12)
print("Original:", arr)

# Reshape
reshaped = arr.reshape(3, 4)
print("\nReshaped (3x4):")
print(reshaped)

# Flatten
flattened = reshaped.flatten()
print("\nFlattened:", flattened)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical stack (vstack):")
print(np.vstack([a, b]))

print("\nHorizontal stack (hstack):")
print(np.hstack([a, b]))

Vertical stack (vstack):
[[1 2 3]
 [4 5 6]]

Horizontal stack (hstack):
[1 2 3 4 5 6]


### 3.4 Indexing & Slicing

Just like Python lists, but more powerful. You can access elements using `[row, col]`. You can also slice ranges `[start:end]`.

In [30]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr)

print("\narr[0, 2] (row 0, col 2):", arr[0, 2])
print("arr[:, 1] (all rows, col 1):", arr[:, 1])
print("arr[1, :] (row 1, all cols):", arr[1, :])
print("arr[0:2, 1:3] (submatrix):")
print(arr[0:2, 1:3])

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr[0, 2] (row 0, col 2): 3
arr[:, 1] (all rows, col 1): [ 2  6 10]
arr[1, :] (row 1, all cols): [5 6 7 8]
arr[0:2, 1:3] (submatrix):
[[2 3]
 [6 7]]


### 3.5 Boolean Indexing (Filtering)

This is a superpower of NumPy. You can filter data using conditions (e.g., "Give me all values greater than 5").

In [31]:
# Boolean indexing (filtering)
print("Elements > 5:", arr[arr > 5])
print("Elements between 3 and 9:", arr[(arr >= 3) & (arr <= 9)])

Elements > 5: [ 6  7  8  9 10 11 12]
Elements between 3 and 9: [3 4 5 6 7 8 9]


### 3.6 Statistics

NumPy has built-in functions for quick statistical analysis.

In [32]:
data = np.array([23, 45, 12, 67, 34, 89, 21, 56])

print("Data:", data)
print("\nMean:", np.mean(data))
print("Std Dev:", np.std(data))

Data: [23 45 12 67 34 89 21 56]

Mean: 43.375
Std Dev: 24.46904932767107


### 3.7 Broadcasting

**Broadcasting** is how NumPy handles arrays with different shapes during arithmetic operations.

Example: Adding a scalar (10) to a vector adds 10 to *every* element of the vector. The scalar is "broadcasted" to match the vector's shape.

In [33]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Scalar broadcasting
print("arr + 10:")
print(arr + 10)

# Vector broadcasting
row = np.array([10, 20, 30])
print("\narr + [10, 20, 30]:")
print(arr + row)

arr + 10:
[[11 12 13]
 [14 15 16]]

arr + [10, 20, 30]:
[[11 22 33]
 [14 25 36]]


---
## 4. Introduction to Tensors

You often hear about **Tensors** in Deep Learning (TensorFlow, PyTorch). 
A Tensor is simply a generalization of vectors and matrices to higher dimensions.

- **Scalar (0D Tensor):** A single number (e.g., `42`)
- **Vector (1D Tensor):** A list of numbers (e.g., `[1, 2, 3]`)
- **Matrix (2D Tensor):** A grid of numbers (e.g., an Excel sheet)
- **Tensor (3D+ Tensor):** A cube or higher-dimensional array of numbers (e.g., a Stack of images)

### Why Tensors?
Images are 3D Tensors: `(Height, Width, Color_Channels)`.
Videos are 4D Tensors: `(Time, Height, Width, Color_Channels)`.

In [34]:
# Creating a 3D Tensor (3 matrices stacked together)
# Imagine this as a very small color image (2 pixels high, 2 pixels wide, 3 colors RGB)

tensor_3d = np.array([
    [[255, 0, 0], [0, 255, 0]],   # Row 1 (Red pixel, Green pixel)
    [[0, 0, 255], [255, 255, 0]]  # Row 2 (Blue pixel, Yellow pixel)
])

print("3D Tensor:")
print(tensor_3d)

print("\nShape:", tensor_3d.shape)
print("(Height, Width, Channels) -> (2, 2, 3)")
print("Dimensions (ndim):", tensor_3d.ndim)

3D Tensor:
[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]

Shape: (2, 2, 3)
(Height, Width, Channels) -> (2, 2, 3)
Dimensions (ndim): 3


---
## 5. Practical Applications

### 5.1 Solving Linear Equations

Solve: `2x + 3y = 8` and `3x + 4y = 11`

In [35]:
# Ax = b
A = np.array([[2, 3],
              [3, 4]])
b = np.array([8, 11])

x = np.linalg.solve(A, b)
print("Solution (x, y):", x)

# Verify
print("Verification A @ x:", A @ x)

Solution (x, y): [1. 2.]
Verification A @ x: [ 8. 11.]


### 5.2 Data Normalization (Feature Scaling)

In [36]:
# Sample dataset
data = np.array([[100, 0.5],
                 [200, 0.8],
                 [150, 0.6],
                 [300, 0.9]])

# Min-Max Normalization (scales to 0-1)
min_vals = data.min(axis=0)
max_vals = data.max(axis=0)
normalized = (data - min_vals) / (max_vals - min_vals)
print("Min-Max Normalized:")
print(normalized)

# Z-Score Standardization (mean=0, std=1)
mean = data.mean(axis=0)
std = data.std(axis=0)
standardized = (data - mean) / std
print("\nZ-Score Standardized:")
print(standardized)

Min-Max Normalized:
[[0.   0.  ]
 [0.5  0.75]
 [0.25 0.25]
 [1.   1.  ]]

Z-Score Standardized:
[[-1.18321596 -1.26491106]
 [ 0.16903085  0.63245553]
 [-0.50709255 -0.63245553]
 [ 1.52127766  1.26491106]]


### 5.3 Cosine Similarity (Used in NLP & Recommendations)

In [37]:
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

vec1 = np.array([1, 2, 3])
vec2 = np.array([1, 2, 3])  # identical
vec3 = np.array([3, 2, 1])  # different

print("Similarity (vec1, vec2):", cosine_similarity(vec1, vec2))
print("Similarity (vec1, vec3):", cosine_similarity(vec1, vec3))

Similarity (vec1, vec2): 1.0
Similarity (vec1, vec3): 0.7142857142857143


---
## Summary

| Concept | Meaning |
|---------|---------|
| **Vectors** | 1D Lists, used for basic features |
| **Matrices** | 2D Grids, used for datasets |
| **Dot Product** | Essential for Neural Network calculations |
| **Broadcasting** | NumPy's magic to handle different shapes |
| **Tensors** | 3D+ Arrays, key for Deep Learning (Images, Video) |